#!/bin/bash
set -Ceu

cat << EOS
    
Usage:
   `basename $0` [doc type]
    
        doc type: ar (article), book

EOS

TEMPLATE_DB=/Users/siida/Dropbox/01code/software/myTools/latex/templates

doc_type=$1
if [ $doc_type == "ar" ]; then
    cp ${TEMPLATE_DB}/template_article.tex ${PWD}/article.tex
    echo "~article.tex was created~"

elif [ $doc_type == "book" ]; then
    cp ${TEMPLATE_DB}/template_book.tex ${PWD}/book.tex
    echo "~book.tex was created~"

fi
